# Generated by Django 4.2.6 on 2023-11-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaNavio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nave', models.CharField(max_length=255)),
                ('Viaje', models.CharField(max_length=255)),
                ('Puerto', models.CharField(max_length=255)),
                ('Carga', models.CharField(max_length=255)),
                ('Procedencia', models.CharField(max_length=255)),
                ('TipoServicio', models.CharField(max_length=255)),
                ('Armador', models.CharField(max_length=255)),
                ('Agencia', models.CharField(max_length=255)),
                ('ProximoPuerto', models.CharField(max_length=255)),
                ('Encalado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('ETA', models.DateField()),
                ('horaRegistroETA', models.TimeField()),
                ('Bombasumergible', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('Cubierta', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('ShapeBox', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('PCR', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('horaRegistroPCR', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cantidadPersonas', models.IntegerField()),
                ('puerto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(default='Nombre Predeterminado', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
