# Generated by Django 4.2.6 on 2023-11-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichanavio',
            name='Estado',
            field=models.CharField(choices=[('Terminado', 'Terminado'), ('En Proceso', 'En Proceso'), ('No Iniciado', 'No Iniciado')], default='No Iniciado', max_length=20),
        ),
    ]
