# Generated by Django 4.2.6 on 2023-11-14 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos_adjuntos/')),
            ],
        ),
        migrations.CreateModel(
            name='FichaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12)),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo')], max_length=10)),
                ('nacionalidad', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('afp', models.CharField(max_length=255)),
                ('salud', models.CharField(max_length=255)),
                ('otros_previsionales', models.CharField(max_length=255)),
                ('tipo_cuenta', models.CharField(max_length=255)),
                ('numero_cuenta', models.CharField(max_length=255)),
                ('banco', models.CharField(choices=[('', 'Selecciona Banco'), ('BCI', 'BCI'), ('Banco Estado', 'Banco Estado')], max_length=20)),
                ('contacto_emergencia_nombre', models.CharField(max_length=255)),
                ('contacto_emergencia_celular', models.CharField(max_length=20)),
                ('contacto_emergencia_parentesco', models.CharField(max_length=255)),
                ('talla_polera', models.CharField(max_length=2)),
                ('talla_pantalon', models.CharField(max_length=2)),
                ('calzado_seguridad', models.IntegerField()),
                ('talla_overol', models.CharField(max_length=2)),
                ('talla_traje_agua', models.CharField(max_length=2)),
                ('documentos', models.ManyToManyField(to='erp.documentoadjunto')),
            ],
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12)),
                ('apellido_paterno_hijo', models.CharField(max_length=255)),
                ('apellido_materno_hijo', models.CharField(max_length=255)),
                ('fecha_nacimiento_hijo', models.DateField()),
                ('parentesco', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('', 'Selecciona Sexo'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('ficha_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.fichapersonal')),
            ],
        ),
    ]
