# Generated by Django 4.2.6 on 2023-11-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(default='Nombre Predeterminado', max_length=255),
        ),
    ]
