# Generated by Django 4.2.6 on 2023-11-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_fichanavio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichanavio',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
