# Generated by Django 4.2.6 on 2023-11-19 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_fichanavio_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichanavio',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
