# Generated by Django 4.2.6 on 2023-11-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_fichanavio_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichanavio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
