# Generated by Django 4.2.6 on 2023-11-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_fichanavio_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En Operacion', 'En Operacion'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=20)),
                ('color', models.CharField(default='#00FF00', max_length=20)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo')], max_length=20)),
                ('nacionalidad', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('afp', models.CharField(max_length=255)),
                ('salud', models.CharField(max_length=255)),
                ('otros_previsionales', models.CharField(max_length=255)),
                ('tipo_cuenta_bancaria', models.CharField(max_length=255)),
                ('numero_cuenta_bancaria', models.CharField(max_length=255)),
                ('banco', models.CharField(choices=[('', 'Selecciona Banco'), ('BCI', 'BCI'), ('Banco Estado', 'Banco Estado')], max_length=255)),
                ('contacto_emergencia_nombre', models.CharField(max_length=255)),
                ('contacto_emergencia_celular', models.CharField(max_length=20)),
                ('contacto_emergencia_parentesco', models.CharField(max_length=255)),
                ('talla_polera', models.CharField(choices=[('', 'Selecciona Talla'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=5)),
                ('talla_pantalon', models.CharField(choices=[('', 'Selecciona Talla'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=5)),
                ('calzado_seguridad', models.IntegerField()),
                ('talla_overol', models.CharField(choices=[('', 'Selecciona Talla'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=5)),
                ('talla_traje_agua', models.CharField(choices=[('', 'Selecciona Talla'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=5)),
                ('documentos', models.FileField(upload_to='documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('ficha_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.fichapersonal')),
            ],
        ),
        migrations.AddField(
            model_name='fichapersonal',
            name='hijos',
            field=models.ManyToManyField(blank=True, to='erp.hijo'),
        ),
    ]
