# Generated by Django 4.2.6 on 2023-11-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_fichapersonal_hijo_fichapersonal_hijos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaHerramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('modelo', models.CharField(max_length=255)),
                ('cantidad_herramientas', models.IntegerField()),
                ('tipo_herramienta', models.CharField(choices=[('Manual', 'Manual'), ('Mecanico', 'Mecanico')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FichaQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_quimico', models.CharField(choices=[('OCN 01', 'OCN 01'), ('OCN 08', 'OCN 08'), ('Acido Clorhídrico', 'Acido Clorhídrico'), ('Hipoclorito', 'Hipoclorito'), ('Hold Coat', 'Hold Coat')], default='OCN 01', max_length=50)),
                ('fecha_registro', models.DateField()),
                ('capacidad_bines', models.CharField(default='Lleno (1000 lts) aprox', max_length=255)),
                ('lugar_almacenamiento', models.CharField(default='Taller', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FichaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('modelo', models.CharField(max_length=255)),
                ('patente', models.CharField(max_length=10)),
                ('chasis', models.CharField(max_length=255)),
                ('tipo_vehiculo', models.CharField(choices=[('', 'Seleccione un tipo de vehículo'), ('Auto', 'Auto'), ('Camioneta', 'Camioneta'), ('Furgon', 'Furgon'), ('Camion', 'Camion')], max_length=50)),
                ('tipo_combustible', models.CharField(choices=[('', 'Seleccione un tipo de combustible'), ('Diesel', 'Diesel'), ('Bencinero', 'Bencinero')], max_length=50)),
            ],
        ),
    ]
