# Generated by Django 4.2.6 on 2023-11-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_fichaherramientas_fichaquimico_fichavehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichanavio',
            old_name='puerto',
            new_name='CantidadPuerto',
        ),
    ]
