# Generated by Django 4.2.6 on 2023-11-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_rename_puerto_fichanavio_cantidadpuerto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('', 'Seleccione una Categoria'), ('Vehiculo', 'Vehiculo'), ('Herramienta', 'Herramienta'), ('Motonave', 'Motonave')], max_length=50)),
                ('accion', models.CharField(choices=[('', 'Seleccione una accion'), ('Mantenimiento', 'Mantenimiento'), ('Revision', 'Revision')], max_length=50)),
                ('estado', models.CharField(choices=[('', 'Seleccione un estado'), ('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], max_length=50)),
            ],
        ),
    ]
